import React from "react";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import StyledComponentsRegistry from "@/lib/AntRegistry";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={`${inter.className} overflow-y-scroll overflow-x-hidden`}>
      <StyledComponentsRegistry>
        <div className="mx-auto text-2xl gap-2 mb-10">
          <Navbar />
          {children}
          <Footer />
        </div>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
